### ISSUE TITLE
Bug 1050850 - In rhsm GUI "System->View System Facts" window, "Update Facts" doesn't work.

### ISSUE THREAD

**Issue by fsharath** [RedHatQE/rhsm-qe#389]
https://bugzilla.redhat.com/show_bug.cgi?id=1050850

**Comment by jstavel** [comment]
This issue has been already solved by test `verify_update_facts`.
(see https://github.com/RedHatQE/rhsm-qe/blob/master/src/rhsm/gui/tests/facts_tests.clj#L291)
