### ISSUE TITLE
Bug 857147 - Auto-subscribe window has a confusing name

### ISSUE THREAD

**Issue by fsharath** [RedHatQE/rhsm-qe#392]
https://bugzilla.redhat.com/show_bug.cgi?id=857147

**Comment by Lorquas** [comment]
Most of this was automated with https://github.com/RedHatQE/rhsm-qe/pull/531 , need to add the blocked by bugs

**Comment by rarebreed** [comment]
Fixed in commit 84e1561a9c6fca8b2b32b553d68930f4207a350d
