### ISSUE TITLE
Bug 1248749 - Products in My Subscriptions tab and All Available Subscriptions takes awhile to match

### ISSUE THREAD

**Issue by Lorquas** [RedHatQE/rhsm-qe#451]
https://bugzilla.redhat.com/show_bug.cgi?id=1248749

If a user looks at the All Available Subscriptions tab, selects a subscription, and checks the Products information, this should be the same as appears under the My Subscriptions tab.  However, after newly attaching a subscription, it can take a minute or two for all the products to show up in the My Subscriptions tab.  This may be disconcerting to customers

**Comment by rarebreed** [comment]
With the latest subscription-manager-gui-1.15.9-15.el7.x86_6 this does not seem to be an issue.  After attaching a subscription I do not notice any lag in the My Subscriptions tab.  Tried this on both a local candlepin instance, as well as production
