### ISSUE TITLE
￼ Bug 1248664 - gui shows warnings to console: Gtk-WARNING **: No object called: 0 0 1 0.10000000000000001 0.90000000000000002 1 

### ISSUE THREAD

**Issue by Lorquas** [RedHatQE/rhsm-qe#462]
https://bugzilla.redhat.com/show_bug.cgi?id=1248664

On startup, the gui logs several warnings:

(subscription-manager-gui:28289): Gtk-WARNING **: No object called: 0 0 1 0.10000000000000001 0.90000000000000002 1

(subscription-manager-gui:28289): Gtk-WARNING **: No object called: 0 0 396 39.600000000000001 356.40000000000003 396

(subscription-manager-gui:28289): Gtk-WARNING **: No object called: 37 0 116 7.9000000000000004 71.100000000000009 79

(subscription-manager-gui:28289): Gtk-WARNING **: No object called: 0 0 206 20.600000000000001 185.40000000000001 206

(subscription-manager-gui:28289): Gtk-WARNING **: No object called: 0 0 1 0.10000000000000001 0.90000000000000002 1

**Comment by jstavel** [comment]
fixed. closed.
