### ISSUE TITLE
Bug 1141128 - Subscription-manager-gui doesnot remove the imported certificate

### ISSUE THREAD

**Issue by Lorquas** [RedHatQE/rhsm-qe#501]
https://bugzilla.redhat.com/show_bug.cgi?id=1141128

**Comment by rarebreed** [comment]
see https://github.com/RedHatQE/rhsm-qe/pull/509

**Comment by rarebreed** [comment]
see 8d06c92620a06aa6a5dcbb49a1c17bb721674b3b
