### ISSUE TITLE
Bug 1240553 - Imported cert doesnot feature in the MySubscriptions Tab of GUI but it does show up when list --consumed command is executed 

### ISSUE THREAD

**Issue by Lorquas** [RedHatQE/rhsm-qe#502]
https://bugzilla.redhat.com/show_bug.cgi?id=1240553

**Comment by rarebreed** [comment]
Closed as of 8d60a5e3f009631cc22cd44d9b4d6d44eb9feeaa

**Comment by rarebreed** [comment]
see https://github.com/RedHatQE/rhsm-qe/pull/509

**Comment by rarebreed** [comment]
closed in 8d06c92620a06aa6a5dcbb49a1c17bb721674b3b
