### ISSUE TITLE
RHEL7-38384 - RHSM : GUI - Verify the columns in subscription-manager gui tables are sortable

### ISSUE THREAD

**Issue by rarebreed** [RedHatQE/rhsm-qe#515]
Verify that each column in the GUI tables are sortable

My Installed Products tab:
- Product
- Version
- Status
- Start Date
- End Date

My Subscriptions tab:
- Subscription
- End Date
- Quantity

All Available Subscriptions tab:
- Subscription
- Type
- Available Subscriptions

**Comment by jstavel** [comment]
It was solved by https://github.com/RedHatQE/rhsm-qe/pull/609
