### ISSUE TITLE
Bug 1278472 - [RFE] change default registration url to subscription.rhsm.redhat.com

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/rhsm-qe#517]
Verify that clicking the "Default" button on the registration panel for specifying the server now defaults to "subscription.rhsm.redhat.com" instead of the former "subscription.rhn.redhat.com".

This change follows subscription-manager-1.16.4-1

**Comment by rarebreed** [comment]
There is a test for this in the GUI:  see https://github.com/RedHatQE/rhsm-qe/pull/524
