### ISSUE TITLE
Bug 1298327 - Status Cache not used when listing repos with a bad proxy

### ISSUE THREAD

**Issue by jstavel** [RedHatQE/rhsm-qe#526]
Subscription manager should list repos even it cannot connect to server.

1) Register without a proxy
2) `subscription-manager repos --list`
3) `subscription-manager repos --list --proxy=auto-services.usersys.redhat.com:3128 --proxyuser=bad-username --proxypassword=bad-password`

test:

subscription-manager status
subscription-manager repos --list | grep "Repo ID" | wc -l
subscription-manager repos --list --proxy=auto-services.usersys.redhat.com:3128 --proxyuser=redhat --proxypassword=badpasswd | grep "Repo ID" | wc -l

#+RESULTS:
: +-------------------------------------------+
:    System Status Details
: +-------------------------------------------+
: Overall Status: Current
:
: 61
: 61

**Comment by jstavel** [comment]
(bugzilla "https://bugzilla.redhat.com/show_bug.cgi?id=1298327")

**Comment by skallesh** [comment]
covered in commit 
https://github.com/RedHatQE/rhsm-qe/pull/549/commits/4d6e9e382995252cb52f9ff5983b558d7499d16d
