### ISSUE TITLE
Bug 1179727 - RFE: Support Per-SKU Enabled/Disabled Content Overrides

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/rhsm-qe#537]
Develop automated test coverage for this RFE https://bugzilla.redhat.com/show_bug.cgi?id=1179727

Etherpad of testcases:
http://etherpad.corp.redhat.com/jgn9ZrC1uM

Polarion testcases:
https://polarion.engineering.redhat.com/polarion/#/project/RedHatEnterpriseLinux7/wiki/RHSMQE/RHSM_SKU%20level%20content%20override?tree_depth=0&tab=tree

Sprint Review:
https://engineering.redhat.com/trac/Entitlement/wiki/SprintReviews/EntitlementSprint87Review

Sprint Recording:
​https://sas.elluminate.com/m.jnlp?sid=819&password=M.B5266630426A7BA71316960CBA313C

**Comment by skallesh** [comment]
https://github.com/skallesh/rhsm-qe/blob/8373ac84c00643b15196dff74c7ee705b08692a1/src/rhsm/cli/tests/SKULevelContentOverrides.java

**Comment by skallesh** [comment]
Bug is automated
