### ISSUE TITLE
Bug in RHEL 7.3 with registration.  Locator name for Register Dialog changed to "register_dialog" again

### ISSUE THREAD

**Issue by rarebreed** [RedHatQE/rhsm-qe#545]
In RHEL 7.2, the locator name for the Register Dialog was named register_dialog.  In 6.8, this changed to "System Registration", so the rhsm.gui.tasks.ui/windows var was changed:

:register-dialog "System Registration"

But it has reverted back to "register_dialog" for RHEL 7.3.  Because the locator name no longer matches, the tests can not find the Register Dialog window now.  

I propose that instead of just changing :register-dialog back to "register_dialog", we write a function that detects the version of RHEL, and creates a new version of windows.  Eg 

```clojure
(def windows-initial ;... same as windows currently)

(defn get-versioned-window 
  "Takes the initial window values, and returns a new map based on RHEL version"
  [init-window]
  ;...
)

(def windows (get-versioned-window windows-initial))
```

**Comment by jstavel** [comment]
Closing, this has been already solved.
